spring:
  profiles: 
    active: 
    - dev 
---
spirng:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-atguigu-dev
    
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-atguigu-test
 
#请使用utf-8保存
